up:
  - ruby: 2.3.1
  - node:
      version: v7.1.0
      yarn: true
      packages: [frontend]
  - bundler
commands:
  test:          bundle exec bin/testunit
  build:         gem build *.gemspec
  frontend:      'cd frontend && ./node_modules/.bin/babel-node ./server.js'
open:
  app: http://localhost:3000
